"""atualiza veiculos

Revision ID: 45ea1996ce2f
Revises: 9342d10d69d6
Create Date: 2026-07-06 14:06:53.116326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ea1996ce2f'
down_revision = '9342d10d69d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ano_fabricacao', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('ano_modelo', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('cambio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('portas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lugares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_fipe', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('proprietario', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('foto_principal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.drop_column('ano')
        batch_op.drop_column('valor_mensal')
        batch_op.drop_column('valor_semanal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_semanal', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_mensal', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('observacoes')
        batch_op.drop_column('foto_principal')
        batch_op.drop_column('proprietario')
        batch_op.drop_column('valor_fipe')
        batch_op.drop_column('lugares')
        batch_op.drop_column('portas')
        batch_op.drop_column('cambio')
        batch_op.drop_column('ano_modelo')
        batch_op.drop_column('ano_fabricacao')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
