"""cria tabela veiculos

Revision ID: 9342d10d69d6
Revises: 08052eb5e3e7
Create Date: 2026-07-06 14:00:49.405088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9342d10d69d6'
down_revision = '08052eb5e3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.String(length=10), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('combustivel', sa.String(length=50), nullable=True),
    sa.Column('renavam', sa.String(length=50), nullable=True),
    sa.Column('chassi', sa.String(length=80), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('valor_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_semanal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos')
    # ### end Alembic commands ###
