"""Adiciona status ativo ao cliente

Revision ID: 9614573d2978
Revises: e526b88a3f7a
Create Date: 2026-07-20 14:07:28.513339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9614573d2978'
down_revision = 'e526b88a3f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'ativo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

        batch_op.alter_column(
            'ativo',
            server_default=None
        )

    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabricante', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('pais_origem', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('segmento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_column('ordem')
        batch_op.drop_column('cor')
        batch_op.drop_column('logo')
        batch_op.drop_column('segmento')
        batch_op.drop_column('pais_origem')
        batch_op.drop_column('fabricante')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
