"""Adiciona status ativo ao cliente

Revision ID: 9614573d2978
Revises: e526b88a3f7a
Create Date: 2026-07-20 14:07:28.513339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9614573d2978'
down_revision = 'e526b88a3f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'ativo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

        batch_op.alter_column(
            'ativo',
            server_default=None
        )

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
