"""estrutura principal

Revision ID: a616a3a11b94
Revises: 45ea1996ce2f
Create Date: 2026-07-06 14:56:43.547559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a616a3a11b94'
down_revision = '45ea1996ce2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_cnh', sa.String(length=30), nullable=True),
    sa.Column('categoria_cnh', sa.String(length=10), nullable=True),
    sa.Column('validade_cnh', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('chave_pix', sa.String(length=150), nullable=True),
    sa.Column('foto_cliente', sa.String(length=255), nullable=True),
    sa.Column('foto_cnh', sa.String(length=255), nullable=True),
    sa.Column('comprovante_residencia', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('valor_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_caucao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('codigo_transacao', sa.String(length=200), nullable=True),
    sa.Column('webhook_recebido', sa.Boolean(), nullable=True),
    sa.Column('comprovante', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_veiculo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_motorizacao', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('combustivel_padrao', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cambio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('portas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lugares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidade_bateria', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('autonomia_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_conector', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('potencia_recarga_kw', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pbt', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('capacidade_carga', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('quantidade_eixos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tracao', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('capacidade_passageiros', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelos', schema=None) as batch_op:
        batch_op.drop_column('capacidade_passageiros')
        batch_op.drop_column('tracao')
        batch_op.drop_column('quantidade_eixos')
        batch_op.drop_column('capacidade_carga')
        batch_op.drop_column('pbt')
        batch_op.drop_column('potencia_recarga_kw')
        batch_op.drop_column('tipo_conector')
        batch_op.drop_column('autonomia_km')
        batch_op.drop_column('capacidade_bateria')
        batch_op.drop_column('lugares')
        batch_op.drop_column('portas')
        batch_op.drop_column('cambio')
        batch_op.drop_column('combustivel_padrao')
        batch_op.drop_column('tipo_motorizacao')
        batch_op.drop_column('tipo_veiculo')

    op.drop_table('pagamentos')
    op.drop_table('parcelas')
    op.drop_table('locacoes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
