"""adiciona chave pix na conta

Revision ID: c196c7ca9e23
Revises: 4133e50bc446
Create Date: 2026-07-07 22:00:17.493953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c196c7ca9e23'
down_revision = '4133e50bc446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('chave_pix')

    # ### end Alembic commands ###
