"""cria tabela negociacoes

Revision ID: c56330d737f0
Revises: c7f59c5de16a
Create Date: 2026-07-07 18:51:14.815263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56330d737f0'
down_revision = 'c7f59c5de16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('novo_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento_original', sa.Date(), nullable=False),
    sa.Column('novo_vencimento', sa.Date(), nullable=False),
    sa.Column('juros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data_negociacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negociacoes')
    # ### end Alembic commands ###
