"""despesas

Revision ID: c7f59c5de16a
Revises: a616a3a11b94
Create Date: 2026-07-06 18:17:08.292772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f59c5de16a'
down_revision = 'a616a3a11b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('juros', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('multa', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('desconto')
        batch_op.drop_column('multa')
        batch_op.drop_column('juros')

    op.drop_table('despesas')
    # ### end Alembic commands ###
