"""configuracoes pix

Revision ID: d256161688ae
Revises: c196c7ca9e23
Create Date: 2026-07-09 14:00:39.414140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd256161688ae'
down_revision = 'c196c7ca9e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_chave_pix', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('favorecido_pix', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('banco_pix', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('banco_pix')
        batch_op.drop_column('favorecido_pix')
        batch_op.drop_column('tipo_chave_pix')

    # ### end Alembic commands ###
