"""Estrutura inicial

Revision ID: e526b88a3f7a
Revises: 
Create Date: 2026-07-10 14:54:23.304103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e526b88a3f7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('cor_primaria', sa.String(length=20), nullable=True),
    sa.Column('chave_pix', sa.String(length=255), nullable=True),
    sa.Column('tipo_chave_pix', sa.String(length=30), nullable=True),
    sa.Column('favorecido_pix', sa.String(length=150), nullable=True),
    sa.Column('banco_pix', sa.String(length=100), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_cnh', sa.String(length=30), nullable=True),
    sa.Column('categoria_cnh', sa.String(length=10), nullable=True),
    sa.Column('validade_cnh', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('chave_pix', sa.String(length=150), nullable=True),
    sa.Column('foto_cliente', sa.String(length=255), nullable=True),
    sa.Column('foto_cnh', sa.String(length=255), nullable=True),
    sa.Column('comprovante_residencia', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('tipo_veiculo', sa.String(length=50), nullable=True),
    sa.Column('tipo_motorizacao', sa.String(length=30), nullable=True),
    sa.Column('combustivel_padrao', sa.String(length=30), nullable=True),
    sa.Column('cambio', sa.String(length=30), nullable=True),
    sa.Column('portas', sa.Integer(), nullable=True),
    sa.Column('lugares', sa.Integer(), nullable=True),
    sa.Column('capacidade_bateria', sa.Integer(), nullable=True),
    sa.Column('autonomia_km', sa.Integer(), nullable=True),
    sa.Column('tipo_conector', sa.String(length=30), nullable=True),
    sa.Column('potencia_recarga_kw', sa.Integer(), nullable=True),
    sa.Column('pbt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacidade_carga', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantidade_eixos', sa.Integer(), nullable=True),
    sa.Column('tracao', sa.String(length=30), nullable=True),
    sa.Column('capacidade_passageiros', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('renavam', sa.String(length=50), nullable=True),
    sa.Column('chassi', sa.String(length=80), nullable=True),
    sa.Column('ano_fabricacao', sa.String(length=4), nullable=True),
    sa.Column('ano_modelo', sa.String(length=4), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('combustivel', sa.String(length=50), nullable=True),
    sa.Column('cambio', sa.String(length=30), nullable=True),
    sa.Column('portas', sa.Integer(), nullable=True),
    sa.Column('lugares', sa.Integer(), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('valor_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_fipe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proprietario', sa.String(length=30), nullable=True),
    sa.Column('foto_principal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('valor_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_caucao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('juros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('novo_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento_original', sa.Date(), nullable=False),
    sa.Column('novo_vencimento', sa.Date(), nullable=False),
    sa.Column('juros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data_negociacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('codigo_transacao', sa.String(length=200), nullable=True),
    sa.Column('webhook_recebido', sa.Boolean(), nullable=True),
    sa.Column('comprovante', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes_negociacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor_proposto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nova_data', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacao_admin', sa.Text(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes_negociacao')
    op.drop_table('pagamentos')
    op.drop_table('negociacoes')
    op.drop_table('parcelas')
    op.drop_table('locacoes')
    op.drop_table('despesas')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_table('modelos')
    op.drop_table('clientes')
    op.drop_table('marcas')
    op.drop_table('contas')
    # ### end Alembic commands ###
